In [2]:
import numpy as np

In [3]:
a_list =[1,2,3,4,5]
type(a_list)

list

In [4]:
np.array(a_list)

array([1, 2, 3, 4, 5])

In [5]:
myarr = np.array(a_list)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

### Zeros and Ones

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [1]:
np.linspace(0,10,5)

NameError: name 'np' is not defined