# NumPy
NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the PyData ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

### Creating NumPy Arrays
#### From a Python List
We can create an array by directly converting a list or list of lists

In [2]:
import numpy as np

In [3]:
a_list =[1,2,3,4,5]
type(a_list)

list

In [4]:
np.array(a_list)

array([1, 2, 3, 4, 5])

In [5]:
myarr = np.array(a_list)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange
Return evenly spaced values within a given inteval ---  [Reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [11]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

### Zeros and Ones
Generate arrays of zeros or ones --  [Reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace

Return evenly spaced numbers over a specified interval. [Reference](https://numpy.org/devdocs/reference/generated/numpy.linspace.html) 

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.linspace(1,10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(0, 5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [21]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye
Create identity matrix [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

#### rand
Crrate an array of the given shape and population it with random samples from a uniform distributor over [0,1]. [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)

In [26]:
np.random.rand(1)

array([0.15430604])

In [27]:
np.random.rand(5, 2)

array([[0.83479327, 0.55062378],
       [0.67668487, 0.35262646],
       [0.40570262, 0.89591881],
       [0.09304552, 0.73493262],
       [0.16934801, 0.37685989]])

In [29]:
np.random.rand(2, 3)

array([[0.31186471, 0.71940052, 0.26056995],
       [0.93488984, 0.15015479, 0.73075706]])

#### randn
Returns a sample from the "standard normal" distribution [σ = 1]. Unlike rand which is uniform, values closer to zero are more likely to appear. [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)

In [30]:
np.random.randn(2,3)

array([[0.93045051, 1.98674044, 0.98683442],
       [0.50194941, 1.81078673, 1.11173699]])

In [31]:
np.random.randn(5)

array([ 1.29992406, -0.57322642, -1.40463916, -1.15123339,  0.17878986])

In [32]:
np.random.randn(5,5)

array([[ 0.59069039, -0.48408254, -0.13994378, -0.19693002,  1.1053814 ],
       [ 0.57052819, -1.06043685, -0.42573686,  0.12368259,  0.20347292],
       [-0.98826385, -0.05595747, -0.40452931,  0.86787173,  0.06423489],
       [-0.92849624, -1.60719106, -2.04917426,  0.80890856,  1.87635248],
       [-1.08089798,  0.15080723,  1.25033996, -0.37200814, -0.52714087]])

#### randint

Returns random integers from low (inclusive) to high --- [reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)

In [33]:
np.random.randint(0,101,5)

array([ 2, 44, 78, 69, 45], dtype=int32)

In [34]:
np.random.randint(50,61,3)

array([52, 60, 53], dtype=int32)

In [35]:
np.random.randint(0, 101, size=(4,5))

array([[44, 67, 20, 64, 10],
       [73, 50, 26, 58, 23],
       [72, 65, 73, 80, 87],
       [74, 24, 53, 20, 31]], dtype=int32)

In [36]:
np.random.randint(0,101,10)

array([95, 53, 70,  4, 77, 57, 15, 97, 68, 36], dtype=int32)

#### seed
can be used to set the random state, so thar thesame " random " results can be reproduced ----- [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html) 

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [40]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

### Array Attributes and Methods
Lets discuss som useful attributes and methods for an array

In [41]:
arr = np.arange(0,25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
arr.reshape(4)

ValueError: cannot reshape array of size 25 into shape (4,)

In [46]:
ranarr = np.random.randint(0,101,10)
ranarr

array([63, 59, 20, 32, 75, 57, 21, 88, 48, 90], dtype=int32)

In [47]:
ranarr.max()

np.int32(90)

In [48]:
ranarr.min()

np.int32(20)

In [49]:
ranarr.argmax() #location index of maximum number where 90 is at index 9

np.int64(9)

#### Reshape 
Returns an array containing the same data with a new shape. [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min, argmax, argmin
These are useful methods for nfinding max or min values. or to find their index locations using argmin or argmax

In [51]:
ranarr

array([63, 59, 20, 32, 75, 57, 21, 88, 48, 90], dtype=int32)

In [52]:
ranarr.max()

np.int32(90)

In [53]:
ranarr.argmax()

np.int64(9)

In [54]:
ranarr.min()

np.int32(20)

In [55]:
ranarr.argmin()

np.int64(2)

### Shape
Shape is an attribute that array have -- [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)

In [56]:
# Vector
arr.shape

(25,)

In [59]:
arr=arr.reshape(5,5)

In [61]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.shape

(5, 5)

In [63]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [64]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### dtype
You can also grab the data type of the object in the array. [[reference]](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)

In [65]:
arr.dtype

dtype('int64')

In [66]:
arr2=np.array([1.2,2.3,4.5])

In [67]:
arr2.dtype

dtype('float64')

In [68]:
arr3=np.array([1.1,2])

In [69]:
arr3.dtype

dtype('float64')